apiVersion: v1
kind: Service
metadata:
  name: tomcat-3001
  namespace: t-dev
spec:
  type: NodePort
  selector:
    app: tomcat-3001
  ports:
  - port: 23001
    targetPort: 23001
    nodePort: 8996
