---
apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
  namespace: default
  labels:
    name: blue
spec:
  replicas: 1
  selector:
    name: blue
  template:
    metadata:
      labels:
        name: blue
    spec:
      containers:
      - name: blue
        image: 192.168.98.121/nginx/lamp:gray
        env:
        - name: VAR_LABEL
          value: 'blue'

---
apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: default
spec:
  type: NodePort
  selector:
    name: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 8101
    name: http
