---
apiVersion: v1
kind: ReplicationController
metadata:
  name: green
  namespace: default
  labels:
    name: green
spec:
  replicas: 1
  selector:
    name: green
  template:
    metadata:
      labels:
        name: green
    spec:
      containers:
      - name: green
        image: 192.168.98.121/nginx/lamp:gray
        env:
        - name: VAR_LABEL
          value: 'green'

---
apiVersion: v1
kind: Service
metadata:
  name: green
  namespace: default
spec:
  type: NodePort
  selector:
    name: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 8100
    name: http
